### ISSUE TITLE
Make Quantization of the image faster(1-8 bit)

### ISSUE THREAD

**Issue by anastasiabolotnikova** [myloginistaken/MobDIP#21]

**Comment by anastasiabolotnikova** [comment]
Quantization a.k.a Bit Plane Slicing is implemented, but it works slow on big images

**Comment by myloginistaken** [comment]
Erase slider after going to the next menu item, otherwise it is still there, for example, for Bicubic. If image is not selected and you try to perform Quantization - app crashes. Slider should fit to the screen (my device has problems with that)
